### ISSUE TITLE
Memory Log always 0

### ISSUE THREAD

**Issue by JoaoRodrigo99** [Waikato/moa#292]
Hey, I'm using MOA to test the different algorthims across various datasets and i want to track their metrics and save them. One of them is memory. When I use other already compiled implementations of MOA, memory measurements works just fine. When I try to build my own using IntelIJ there's no memory estimation. Anyone had similar issue or knows what im missing?
I wanted to be able to compile and check for memory, since i was to be able to add more models to test...

**Comment by hmgomes** [comment]
Hi @JoaoRodrigo99 , I know it took a while to get back to you, but what you are observing is because by default MOA does not include the sizeofag jar file, which is used for the RAM hours estimations. If you want this statistic, you will need to explicitly include it when launching the moa jar, something like: 

```java -cp moa.jar -javaagent:sizeofag.jar ...```

Btw, you can get support quicker by sending it through our discord channel: https://discord.gg/spd2gQJGAb
